<a href="https://colab.research.google.com/github/Deepak-Mewada/TensorFlow-Developer-Certificate-in-2023-Zero-to-Mastery/blob/main/00_tf_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook we are going to cover most fundamental concepts of TenbsorFlow

More specifically,We are going to cover:
* Introduction to tensor
* Getting informaiton from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function(w way to speed up regular poython functions)
* Using GPU with tensorflow
* Exercise to try by yourself


In [1]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.9.2


#Introduction to Tensor

In [2]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimentsion of a tensor() ndim stands for number of dimensions
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#check the dimension of our vector
vector.ndim

1

In [6]:
# create a matrix
matrix= tf.constant([[7.,10],[10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 7., 10.],
       [10.,  7.]], dtype=float32)>

In [7]:
matrix.ndim

2

In [8]:
#create another matrix 
another_matrix = tf.constant([[10.,7],
                              [3,2],
                              [8,9]], dtype=tf.float16) # specify the data
another_matrix                             

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# let's create a tenosr
tensor= tf.constant([[[1,2,2],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]],dtype=tf.int32)

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  2],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we created so far

# Creating with tf.veriable

In [12]:
# creating the same tesnors with tf.veriable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
#changeable_tensor[0]=1

In [14]:
# how anbout we try .assign()
changeable_tensor[0].assign(1)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 7], dtype=int32)>

In [15]:
#unchangeable_tensor[0].assign(7)

### Creating random tensor
Creating random tensors of arbitrary size which contain random numbers.


In [16]:
#### Creating two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1= random_1.normal(shape= (3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))


# are they equal?
random_1, random_2 , random_1== random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the order ofelemnts in a tensor

In [17]:
##  shuffle a tensor
not_shuffled = tf.constant([[10,7],
                           [2,3],
                           [4,5],
                            [1,2],
                            [4,5],
                            [6,7]])

not_shuffled.ndim


2

In [18]:
#shuffle our non-shuffled tensor
tf.random.set_seed(3)
print(tf.random.shuffle(not_shuffled, seed=9))
print(tf.random.shuffle(not_shuffled, seed=9))

tf.Tensor(
[[ 4  5]
 [10  7]
 [ 1  2]
 [ 6  7]
 [ 2  3]
 [ 4  5]], shape=(6, 2), dtype=int32)
tf.Tensor(
[[ 1  2]
 [ 4  5]
 [ 2  3]
 [ 6  7]
 [10  7]
 [ 4  5]], shape=(6, 2), dtype=int32)


In [19]:
not_shuffled

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [ 4,  5],
       [ 1,  2],
       [ 4,  5],
       [ 6,  7]], dtype=int32)>

In [20]:
tf.random.set_seed(1235)
print(tf.random.uniform([1],seed=2))  # generates 'A1'
print(tf.random.uniform([1],seed=2))  # generates 'A2'
print(tf.random.uniform([1],seed=2))

tf.Tensor([0.14347446], shape=(1,), dtype=float32)
tf.Tensor([0.34754717], shape=(1,), dtype=float32)
tf.Tensor([0.5156163], shape=(1,), dtype=float32)


In [21]:
tf.random.set_seed(1235)
print(tf.random.uniform([1],seed=2))  # generates 'A1'
print(tf.random.uniform([1],seed=2))  # generates 'A2'

tf.Tensor([0.14347446], shape=(1,), dtype=float32)
tf.Tensor([0.34754717], shape=(1,), dtype=float32)


# other ways to amke tensors

In [22]:
# create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [23]:
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors



In [24]:
# You can also turn Numpy arrays into tensors
import numpy as np
numpy_A =  np.arange(1,25,dtype=np.int16)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [25]:
A = tf.constant(numpy_A,shape=(3,8))
A

<tf.Tensor: shape=(3, 8), dtype=int16, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int16)>

### Getting information from tensors

* shape

* rank

* Axis

* Size

In [26]:
#create a rank 4 tensor(4 dimensions)
rank_4_tensor= tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [28]:
rank_4_tensor.shape, rank_4_tensor.ndim , tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [29]:
# get vaeious attribute of of our tesnor

print("Datatype of every element:", rank_4_tensor.dtype)
print("Num")

Datatype of every element: <dtype: 'float32'>
Num


#Indexing tensors
Tensors can be indexed just like python lists

In [30]:
#Get the first two elemnts of each dimension
rank_4_tensor[:2,:2,:2,:2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
#get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
#create a rank 2 tensor
rank_2_tensor = tf.constant([[2,3],
                            [4,5]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [33]:
#get the last element of each row of rank 2
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [34]:
# adding an extra dimension to the end of a tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

In [35]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=2)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

### Manipulating tensors(tensor operations)
**basic operations**

`+` `-` `\` `*`

In [39]:
#addition
tensor= tf.constant([[1,2],
                    [3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [44]:
# we can us the tensorflow built-in function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

#Matrix Mulitplicaiton

`matmul`
`tensordot`
`@`

In [53]:
#multiplying matrix
matrix1= tf.constant([[2,3,1],
                      [4,5,2]])

matrix2= tf.constant([[1,2],
                     [3,4],
                     [5,2]
                     ])

tf.linalg.matmul(matrix1,matrix2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 18],
       [29, 32]], dtype=int32)>

In [56]:
matrix1 @ matrix2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 18],
       [29, 32]], dtype=int32)>

In [60]:
matrix1.shape

TensorShape([2, 3])

In [61]:
tf.reshape(matrix2, (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 2]], dtype=int32)>

In [62]:
tf.reshape(matrix1,(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [1, 4],
       [5, 2]], dtype=int32)>

In [63]:
tf.linalg.matmul(matrix1,matrix2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 18],
       [29, 32]], dtype=int32)>

In [67]:
#transpose
tf.transpose(matrix1),matrix1

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 4],
        [3, 5],
        [1, 2]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 3, 1],
        [4, 5, 2]], dtype=int32)>)

In [69]:
tf.matmul(tf.transpose(matrix1),tf.transpose(matrix2))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 22, 18],
       [13, 29, 25],
       [ 5, 11,  9]], dtype=int32)>

### Dot product

Matrix multiplicaiton is alos refered as dost product

In [71]:
tf.tensordot(matrix1,matrix2,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 18],
       [29, 32]], dtype=int32)>

In [74]:
# Perform Matrix multiplicaitonb between X and y
tf.matmul(matrix1,tf.reshape(matrix2,(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12,  7],
       [19, 26, 17],
       [13, 20, 19]], dtype=int32)>

#Changing the datatype of tensor

In [76]:
#change from float32 to float16

B=tf.constant([1,2])
B

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [78]:
D=tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>,
 tf.float16)

In [82]:
# change from int32 to float32
E = tf.cast(D, dtype= tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

#Aggregating tensors

Aggregating tensors = consdesning them from multiple value down to a smaller amount of values

In [83]:
# get the absolute values
D= tf.constant([10,-2])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  2], dtype=int32)>

In [84]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [88]:
tf.math.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [90]:
tf.math.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [92]:
tf.math.reduce_mean(tensor), tf.math.reduce_sum(tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=10>)

In [105]:
tf.math.reduce_variance(tf.cast(tensor,dtype=tf.float16)),tf.math.reduce_std(tf.cast(tensor,dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=float16, numpy=1.25>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.118034>)

#### Find the positional maximum and minimum

In [111]:
#create a new tensor
tf.random.set_seed(12)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.47720265, 0.33357763, 0.4960823 , 0.48351312, 0.2963959 ,
       0.69444907, 0.68488   , 0.6662284 , 0.07551682, 0.06608915,
       0.91428673, 0.21982336, 0.066468  , 0.37987065, 0.88209164,
       0.73124087, 0.59181285, 0.9785874 , 0.0937705 , 0.37701082,
       0.2055552 , 0.2800591 , 0.44172525, 0.9199766 , 0.49873018,
       0.10266078, 0.12177575, 0.10520744, 0.22547913, 0.39156199,
       0.5587522 , 0.7095549 , 0.04214132, 0.03028095, 0.14591146,
       0.7897457 , 0.52633774, 0.8487345 , 0.08758485, 0.5727763 ,
       0.74252594, 0.63061965, 0.03749514, 0.0432719 , 0.13088238,
       0.6540686 , 0.9438777 , 0.65461504, 0.10520577, 0.8353534 ],
      dtype=float32)>

In [112]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=17>

In [114]:
F[tf.argmax(F)] 

<tf.Tensor: shape=(), dtype=float32, numpy=0.9785874>

In [116]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=33>

In [117]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.030280948>

###Sqeezing a tensor(removing all single dimensions)

In [126]:
# create a tensoir to get started
tf.random.set_seed(40)
G= tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G 

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.54513085, 0.7588961 , 0.8362565 , 0.39474642, 0.72001076,
           0.6402768 , 0.15894496, 0.57128036, 0.41122293, 0.18993318,
           0.2312665 , 0.7875649 , 0.18806243, 0.8033031 , 0.12747478,
           0.43258965, 0.98803484, 0.8451586 , 0.9797807 , 0.9952853 ,
           0.6283821 , 0.8643936 , 0.9500631 , 0.41532683, 0.388798  ,
           0.33959448, 0.36432612, 0.79217136, 0.90930283, 0.6459546 ,
           0.4547919 , 0.3669002 , 0.22951639, 0.54661405, 0.9371824 ,
           0.04014015, 0.82825315, 0.45409238, 0.943413  , 0.20978856,
           0.1274836 , 0.9666685 , 0.97015405, 0.568432  , 0.99477863,
           0.39956594, 0.3263564 , 0.61465824, 0.24279046, 0.03102553]]]]],
      dtype=float32)>

In [127]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [130]:
G_squeezed= tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.54513085, 0.7588961 , 0.8362565 , 0.39474642, 0.72001076,
        0.6402768 , 0.15894496, 0.57128036, 0.41122293, 0.18993318,
        0.2312665 , 0.7875649 , 0.18806243, 0.8033031 , 0.12747478,
        0.43258965, 0.98803484, 0.8451586 , 0.9797807 , 0.9952853 ,
        0.6283821 , 0.8643936 , 0.9500631 , 0.41532683, 0.388798  ,
        0.33959448, 0.36432612, 0.79217136, 0.90930283, 0.6459546 ,
        0.4547919 , 0.3669002 , 0.22951639, 0.54661405, 0.9371824 ,
        0.04014015, 0.82825315, 0.45409238, 0.943413  , 0.20978856,
        0.1274836 , 0.9666685 , 0.97015405, 0.568432  , 0.99477863,
        0.39956594, 0.3263564 , 0.61465824, 0.24279046, 0.03102553],
       dtype=float32)>, TensorShape([50]))

## One hot encoding in data mining

In [134]:
#create a list of indices
some_list= [0,1,2,3]  

#one hot encod
tf.one_hot(some_list, depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [138]:
# Specify custom value for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

## Squaring , log, square root of tenosr

In [142]:
# crerate a tenosr
H = tf.range(10)
H

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [143]:
tf.square(H)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [150]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [151]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

### Tensors and Numpy
Tensorflow interact with Numpy array

In [156]:
#create a tenosr from numpy array
J = tf.constant(np.array([3.,7.,8.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 7., 8.])>

In [158]:
np.array(J), type(np.array(J))

(array([3., 7., 8.]), numpy.ndarray)

In [161]:
J.numpy()[1]

7.0

In [166]:
# Default type of each are slightly differewnt 
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_j= tf.constant([2.,4.,5.,6.])

numpy_J.dtype, tensor_j.dtype

(tf.float64, tf.float32)